spring.application.name=tienda2
#Para definir el formato de despliegue de fecha/hora del log en la consola
logging.pattern.dateformat=hh:mm

#Para eliminar mensajes invasivos de Spring
spring.main.banner-mode=off

#En desarrollo el "cache" del servidor (false), en producción "true"
spring.thymeleaf.cache=false

# Conexión local a la BD Techshop en MySQL

#spring.datasource.url=jdbc:mysql://localhost:3306/techshop
#local

# Usuario y clave de creaTablas.sql

#spring.datasource.username=usuario_prueba
#spring.datasource.password=Usuar1o_Clave.


# Mostrar información en el log
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.type.descriptor.sql.BasicBinder=TRACE

#Nube aiven
spring.datasource.url=jdbc:mysql://techshop-alanafernandez0120-f686.d.aivencloud.com:17284/techshop
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_0zeqB1NWV-9PxuFbJFM


# Driver y plataforma de comunicación
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

#firebase

firebase.bucket.name=techshop-30941.firebasestorage.app
firebase.storage.path=techshop
firebase.json.path=firebase
firebase.json.file=techshop-30941-firebase-adminsdk-fbsvc-be492d3dc2.json
